name: "{{wealth_project}}"
version: "1.0.0"
config-version: 2
profile: "{{wealth_project}}"

model-paths: ["models"]
seed-paths: []
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: ["target", "dbt_packages"]


models:
  {{wealth_project}}:
    +materialized: view
    marts:
      +schema: marts
      +access: private
      +materialized: table
