name: "{{insurance_project}}"
version: "1.0.0"
config-version: 2
profile: "{{insurance_project}}"

model-paths: ["models"]
seed-paths: []
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: ["target", "dbt_packages"]


models:
  {{insurance_project}}:
    +materialized: view
    marts:
      +schema: marts
      +access: private
      +materialized: table
