name: "demo_banking_insurance"
version: "1.0.0"
config-version: 2
profile: "demo_banking_insurance"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: ["target", "dbt_packages"]

vars:
  demo_as_of_date: "2026-03-31"

models:
  demo_banking_insurance:
    +materialized: view
    marts:
      +schema: marts
      +access: private
      +materialized: table

seeds:
  demo_banking_insurance:
    +schema: insurance_seeds
