name: "op_financials"
version: "1.0.0"
config-version: 2
profile: "op_financials"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: ["target", "dbt_packages"]

vars:
  demo_as_of_date: "2026-03-31"
  revenue_outlier_warn: 50000
  profit_floor_warn: 0

models:
  op_financials:
    +materialized: view
    marts:
      +schema: marts
      +access: private
      +materialized: table

seeds:
  op_financials:
    +schema: financials_seeds
